version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 15
    groups:
      github-actions-updates:
        applies-to: version-updates
        patterns:
          - "*"
      github-actions-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: weekly
    open-pull-requests-limit: 15
    groups:
      workflow-updates:
        applies-to: version-updates
        patterns:
          - "*"
      workflow-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: weekly
    open-pull-requests-limit: 15
    groups:
      doc-updates:
        applies-to: version-updates
        patterns:
          - "*"
      doc-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
